

```{r libraries}

library(data.table)
library(simplifyNet)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(ggbump)
library(igraph)
library(arcdiagram)
library(knitr)
library(kableExtra)
```

```{r setup}


A <- as.matrix(read.csv("../data/matrix_a_sorted.csv"))
B <- as.matrix(read.csv("../data/matrix_b_sorted.csv"))
C <- as.matrix(read.csv("../data/matrix_c_sorted.csv"))

ranksA <- read.csv("../data/ranks_a.csv")
ranksB <- read.csv("../data/ranks_b.csv")
ranksC <- read.csv("../data/ranks_c.csv")
```

```{r}

tableA <- A
colnames(tableA)[1] <- "Name"
kable(A) %>% kable_styling()

```

```{r demographics}

demo_dfA <- data.frame(
  name = c("HL", "CW", "SX", "HZ", "BH", "GS", "ZM", "BX", "TG", "TT", "HG", 
           "YM", "ES", "YZ", "CL", "FT", "HU", "FM", "HR", "ZL", "TY", "FY", "HH"),
  male = c(T, T, T, T, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, T, T, F, T),
  adult = c(T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F, F, F, F)
)

demo_dfB<- data.frame(
  name = c("HL", "CW", "SX", "HZ", "BH", "GS", "ZM", "BX", "TG", "TT", "HG", 
           "YM", "ES", "YZ", "CL", "FT", "HU", "FM", "HR", "ZL", "TY", "FY", "HH"),
  male = c(T, T, T, T, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, T, T, F, T),
  adult = c(T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, F)
)


demo_dfC<- data.frame(
  name = c("HL", "CW", "SX", "HZ", "BH", "GS", "ZM", "BX", "TG", "TT", "HG", 
           "YM", "ES", "YZ", "CL", "FT", "HU", "FM", "HR", "ZL", "TY", "FY", "HH"),
  male = c(T, T, T, T, F, T, T, F, F, F, T, F, F, F, F, F, F, F, F, T, T, F, T),
  adult = c(T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T, T)
)

demo_dfA <- demo_dfA[match(ranksA$Var1, demo_dfA$name),]
demo_dfB <- demo_dfB[match(ranksB$Var1, demo_dfB$name),]
demo_dfC<- demo_dfC[match(ranksC$Var1, demo_dfC$name),]





```


```{r rank-table}

# ranks table function
create_table <- function(df){
  ranksTableA <- df
  ranksTableA$ranks <- round(ranksTableA$ranks, 3)
  colnames(ranksTableA) <- c("Name", "Rank")
  df_t <- as.data.frame(t(ranksTableA), stringsAsFactors = F)
  df_t %>% kable(format = "html") %>% kable_styling() %>%
  column_spec(1:ncol(df_t), border_left = TRUE, border_right = TRUE) %>%
  row_spec(nrow(df_t), extra_css = "border-bottom: 1px solid black;")
}

create_table(ranksA[1:floor(nrow(ranksA) / 2), ])
create_table(ranksA[floor(nrow(ranksA) / 2 + 1):nrow(ranksA),])


create_table(ranksB[1:floor(nrow(ranksB) / 2), ])
create_table(ranksB[floor(nrow(ranksB) / 2 + 1):nrow(ranksB),])

create_table(ranksC[1:floor(nrow(ranksC ) / 2), ])
create_table(ranksC[floor(nrow(ranksC) / 2 + 1):nrow(ranksC),])
```



```{r bump-chart}

#A_merged = merge(A, ranksA, by = "Var1")
ranksA$time_period = 1
ranksB$time_period = 2
ranksC$time_period = 3

ranksADemo = merge(ranksA, demo_dfA, by.y = "name", by.x = "Var1" )
ranksBDemo = merge(ranksB, demo_dfB, by.y = "name", by.x = "Var1" )
ranksCDemo = merge(ranksC, demo_dfC, by.y = "name", by.x = "Var1" )
all_ranks = rbind(ranksADemo, ranksBDemo, ranksCDemo)

#rank bump chart
transition_points <- all_ranks %>%
  group_by(Var1) %>%
  filter(adult & !lag(adult))

ggplot(all_ranks, aes(x = time_period, y = ranks, group = Var1, color = male)) +
    scale_x_discrete(limits = c("1", "2", "3"),
                     expand = c(0, 0)) +
geom_bump() +
   theme(
    axis.text.x = element_text(size = 20),
    axis.text.y = element_text(size = 20)
  ) + theme(
  legend.text = element_text(size = 8)
) + scale_color_manual(
  values = c("TRUE" = "#413BFF", "FALSE" = "#FF3BFC"),
  labels = c("FALSE" = "Female", "TRUE" = "Male"),
  name = "Sex") +
 scale_alpha_manual(
   values = c("TRUE" = 1),
   labels = c("TRUE" = "Matures"),
   name = "Age"
   ) + geom_point(data = transition_points,
           aes(x = time_period - 0.02, y = ranks, alpha = adult),
           size = 3,
           shape = 21,
           inherit.aes = FALSE,
           fill = "black")
```


```{r avg_rank}

#find average rank change
ranks_wide <- all_ranks %>% pivot_wider(names_from = time_period, values_from = ranks)

ranks_wide$change <- abs(ranks_wide$`3` - ranks_wide$`1`)
change_df <- ranks_wide %>% filter(!is.na(change))
print(mean(change_df$change))

                                        

```


```{r convert-to-matrix}
#remove na values, convert to matrix form
 convert_to_mat <- function(df){
df <- df[, -1]
  df[is.na(df)] <- 0
  #rownames(df) = colnames(df)

  return(df)
}

```


```{r}

#plot network demographic chart
set.seed(11)

network <- graph_from_adjacency_matrix(convert_to_mat(A), mode = "directed", weighted = TRUE)

layout <- layout_with_fr(network)
rank_scaled <- scale(ranksA[, 2])
layout[,2] <- rank_scaled

weight_factor = max(E(network)$weight) / 0.8
transp <- (0.2 + E(network)$weight / weight_factor)
plot(network,
     layout = layout,
     vertex.label.cex = 0.7,
     vertex.size = ifelse(demo_dfA$adult, 12, 8),
     edge.width = E(network)$weight / 10,
     edge.arrow.size = 0.2,
     vertex.border = 0,
     vertex.frame.width = 2,
     vertex.color = ifelse(demo_dfA$male, "#DCDBFF", "#FFDBF6"),
    edge.color = rgb(0.3, 0.3, 0.3, transp))

legend("bottomright",
       title = "Sex",
       inset = 0.08,
       legend = c("Male", "Female"), col = c('#DCDBFF', "#FFDBF6"),
       lwd = 3)
legend("topright",
       title = "Age",
       inset = 0.15,
       legend = c("Adult", "Subadult"), pch = 21, pt.cex = c(4, 2))

```


```{r edges}

# create data frame with edge list and weight
edges <- get.edgelist(network)
edge_df <- as.data.frame(edges)

edge_df$ind1 = match(edge_df$V1, colnames(A[,-1]))
 elist <- Mtrx_EList(A[, -1], directed = T)
weighted_edges = merge(edge_df, elist, by.y = c("n1", "n2"), by.x = c("ind1", "ind2"))
weighted_edges$weight <- as.integer(weighted_edges$weight)


```

```{r}

#plot arcdiagram
edge_mask <- which(weighted_edges$ind1 < weighted_edges$ind2)
winning_df <- weighted_edges %>% filter(
  ind1 < ind2
)
print(sum(winning_df$weight))
print(sum(weighted_edges$weight))

weight_factor = max(weighted_edges$weight) / 0.8
transp <- (0.2 + weighted_edges$weight / weight_factor)
edges <- as.matrix(weighted_edges[,3:4])

edge_color <- ifelse(weighted_edges$ind1 < weighted_edges$ind2, rgb(0.75, 0.8, 1, transp), rgb(1, 0.25, 0.25, transp))

ranked_names <- rev(ranksA[[1]])

arcplot(edges, las=2,font = 1, col.arcs = edge_color,
        above = above_below(edges, edge_mask), ordering = ranked_names, horizontal = F,
        lwd.arcs = 2, pch.nodes = 19, sorted = T, decreasing = F
        ) 
legend("topright",
       title = "Dominant Node in Interaction",
       legend = c("Higher ranked", "Lower ranked"), col = c(rgb(0.75, 0.8, 1, 1), rgb(1, 0.25, 0.25, 1)),
       lwd = 3)


```
